import { execFile as execFileCallback } from 'child_process'
import { mkdtemp, readFile, readdir, realpath, rm, stat, symlink, writeFile } from 'fs/promises'
import { tmpdir } from 'os'
import { join } from 'path'
import { promisify } from 'util'
import { describe, expect, it } from 'vitest'
import { projectEnvFilePartialResult, writeProjectEnvFile } from './envFile'

const execFile = promisify(execFileCallback)

describe('env file writer', () => {
  it('serializes env entries and creates a gitignore when requested', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      const result = await writeProjectEnvFile({
        projectPath: dir,
        entries: [
          { envKey: 'API_KEY', value: 'secret with spaces' },
          { envKey: 'SHELLY', value: 'uses $TOKEN and `cmd`' },
          { envKey: 'EMPTY', value: '' },
        ],
        addToGitignore: true,
      })

      expect(result.targetFolder).toBe(await realpath(dir))
      expect(result.safeEntries).toEqual([
        { envKey: 'API_KEY', value: 'secret with spaces' },
        { envKey: 'SHELLY', value: 'uses $TOKEN and `cmd`' },
        { envKey: 'EMPTY', value: '' },
      ])
      expect(result.status).toEqual({ envFile: 'created', gitignore: 'created' })
      expect(await readFile(join(dir, '.env'), 'utf8')).toBe(
        '# Generated by Vaultage - do not commit this file\nAPI_KEY="secret with spaces"\nSHELLY="uses \\$TOKEN and \\`cmd\\`"\nEMPTY=""\n',
      )
      expect(await readFile(join(dir, '.gitignore'), 'utf8')).toBe('.env\n')
      expect((await stat(join(dir, '.env'))).mode & 0o777).toBe(0o600)
      expect((await stat(join(dir, '.gitignore'))).mode & 0o777).toBe(0o600)
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('does not duplicate an existing .env gitignore entry', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await writeFile(join(dir, '.gitignore'), 'node_modules\n.env\n')
      await writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'secret' }],
        addToGitignore: true,
      })

      expect(await readFile(join(dir, '.gitignore'), 'utf8')).toBe('node_modules\n.env\n')
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('validates project paths and env entries before writing', async () => {
    await expect(writeProjectEnvFile({
      projectPath: 'relative/path',
      entries: [{ envKey: 'GOOD', value: 'x' }],
      invalidPathMessage: 'Invalid project folder',
    })).rejects.toThrow('Invalid project folder')

    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'bad-key', value: 'x' }],
      })).rejects.toThrow('Invalid env key: bad-key')
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('requires explicit replacement approval before changing .env or .gitignore', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await writeFile(join(dir, '.env'), 'EXISTING=keep\n')
      let caught: unknown
      try {
        await writeProjectEnvFile({
          projectPath: dir,
          entries: [{ envKey: 'API_KEY', value: 'new' }],
          addToGitignore: true,
        })
      } catch (error) {
        caught = error
      }
      expect(caught).toBeInstanceOf(Error)
      expect((caught as Error).message).toContain('explicitly approve replacing')
      expect(projectEnvFilePartialResult(caught)).toEqual({
        envFile: 'not-written',
        gitignore: 'not-updated',
      })
      expect(await readFile(join(dir, '.env'), 'utf8')).toBe('EXISTING=keep\n')
      await expect(readFile(join(dir, '.gitignore'), 'utf8')).rejects.toThrow()

      const replaced = await writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'new' }],
        overwriteExisting: true,
      })
      expect(replaced.status.envFile).toBe('replaced')
      expect(await readFile(join(dir, '.env'), 'utf8')).toContain('API_KEY=new')
      expect((await stat(join(dir, '.env'))).mode & 0o777).toBe(0o600)
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('refuses to write values into a Git-tracked .env even when it is ignored', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await execFile('git', ['init', '--quiet', dir])
      await writeFile(join(dir, '.env'), 'EXISTING=keep\n')
      await execFile('git', ['-C', dir, 'add', '--', '.env'])
      await writeFile(join(dir, '.gitignore'), '.env\n')

      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'new-secret' }],
        addToGitignore: true,
        overwriteExisting: true,
      })).rejects.toThrow('Git-tracked .env')

      expect(await readFile(join(dir, '.env'), 'utf8')).toBe('EXISTING=keep\n')
      expect(await readFile(join(dir, '.gitignore'), 'utf8')).toBe('.env\n')
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('rejects symlink targets and never leaves staging files behind', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    const outside = await mkdtemp(join(tmpdir(), 'vaultage-env-outside-'))
    try {
      const outsideEnv = join(outside, 'target.env')
      await writeFile(outsideEnv, 'DO_NOT_CHANGE=yes\n')
      await symlink(outsideEnv, join(dir, '.env'))

      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'secret' }],
        overwriteExisting: true,
      })).rejects.toThrow('must not be a symbolic link')
      expect(await readFile(outsideEnv, 'utf8')).toBe('DO_NOT_CHANGE=yes\n')
      expect((await readdir(dir)).filter(name => name.includes('.vaultage-'))).toEqual([])
    } finally {
      await rm(dir, { recursive: true, force: true })
      await rm(outside, { recursive: true, force: true })
    }
  })

  it('does not follow a symlinked .gitignore before writing plaintext', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    const outside = await mkdtemp(join(tmpdir(), 'vaultage-gitignore-outside-'))
    try {
      const outsideIgnore = join(outside, 'gitignore')
      await writeFile(outsideIgnore, 'keep-this\n')
      await symlink(outsideIgnore, join(dir, '.gitignore'))

      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'secret' }],
        addToGitignore: true,
      })).rejects.toThrow('must not be a symbolic link')
      expect(await readFile(outsideIgnore, 'utf8')).toBe('keep-this\n')
      await expect(readFile(join(dir, '.env'), 'utf8')).rejects.toThrow()
    } finally {
      await rm(dir, { recursive: true, force: true })
      await rm(outside, { recursive: true, force: true })
    }
  })

  it('rechecks authorization immediately before committing plaintext', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'secret' }],
        authorizeCommit: () => false,
      })).rejects.toThrow('locked before')
      await expect(readFile(join(dir, '.env'), 'utf8')).rejects.toThrow()
      expect((await readdir(dir)).filter(name => name.includes('.vaultage-'))).toEqual([])
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('does not commit plaintext when asynchronous authorization is revoked after staging', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    let checks = 0
    try {
      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'secret' }],
        authorizeCommit: async () => {
          checks += 1
          return checks === 1
        },
      })).rejects.toThrow('locked before')
      expect(checks).toBe(2)
      await expect(readFile(join(dir, '.env'), 'utf8')).rejects.toThrow()
      expect((await readdir(dir)).filter(name => name.includes('.vaultage-'))).toEqual([])
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })
})
