import { mkdtemp, readFile, rm, writeFile } from 'fs/promises'
import { tmpdir } from 'os'
import { join } from 'path'
import { describe, expect, it } from 'vitest'
import { writeProjectEnvFile } from './envFile'

describe('env file writer', () => {
  it('serializes env entries and creates a gitignore when requested', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      const result = await writeProjectEnvFile({
        projectPath: dir,
        entries: [
          { envKey: 'API_KEY', value: 'secret with spaces' },
          { envKey: 'SHELLY', value: 'uses $TOKEN and `cmd`' },
          { envKey: 'EMPTY', value: '' },
        ],
        addToGitignore: true,
      })

      expect(result.targetFolder).toBe(dir)
      expect(result.safeEntries).toEqual([
        { envKey: 'API_KEY', value: 'secret with spaces' },
        { envKey: 'SHELLY', value: 'uses $TOKEN and `cmd`' },
        { envKey: 'EMPTY', value: '' },
      ])
      expect(await readFile(join(dir, '.env'), 'utf8')).toBe(
        '# Generated by Vaultage - do not commit this file\nAPI_KEY="secret with spaces"\nSHELLY="uses \\$TOKEN and \\`cmd\\`"\nEMPTY=""\n',
      )
      expect(await readFile(join(dir, '.gitignore'), 'utf8')).toBe('.env\n')
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('does not duplicate an existing .env gitignore entry', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await writeFile(join(dir, '.gitignore'), 'node_modules\n.env\n')
      await writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'API_KEY', value: 'secret' }],
        addToGitignore: true,
      })

      expect(await readFile(join(dir, '.gitignore'), 'utf8')).toBe('node_modules\n.env\n')
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('validates project paths and env entries before writing', async () => {
    await expect(writeProjectEnvFile({
      projectPath: 'relative/path',
      entries: [{ envKey: 'GOOD', value: 'x' }],
      invalidPathMessage: 'Invalid project folder',
    })).rejects.toThrow('Invalid project folder')

    const dir = await mkdtemp(join(tmpdir(), 'vaultage-env-file-'))
    try {
      await expect(writeProjectEnvFile({
        projectPath: dir,
        entries: [{ envKey: 'bad-key', value: 'x' }],
      })).rejects.toThrow('Invalid env key: bad-key')
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })
})
