import { afterEach, describe, expect, it, vi } from 'vitest'
import { mkdir, mkdtemp, readFile, rm, stat } from 'fs/promises'
import { tmpdir } from 'os'
import { join } from 'path'
import type { IpcMain } from 'electron'
import type { AuthController } from './auth'
import { registerProjectIpc } from './projectIpc'
import { ProjectPathCapabilityStore } from './projectCapabilities'
import { projectIpcContracts } from '../shared/projectIpcContracts'

type IpcHandler = (event: unknown, payload: unknown) => Promise<unknown>

const temporaryFolders: string[] = []

afterEach(async () => {
  await Promise.all(temporaryFolders.splice(0).map(path => rm(path, { recursive: true, force: true })))
})

describe('project .env export IPC', () => {
  it('derives the target, mappings, and gitignore policy from the stored local environment', async () => {
    const folder = await temporaryFolder()
    const harness = exportHarness({ folder })

    const result = await harness.exportEnv()

    expect(result).toMatchObject({
      success: true,
      status: { envFile: 'created', gitignore: 'created' },
    })
    expect(await readFile(join(folder, '.env'), 'utf8')).toBe(
      '# Generated by Vaultage - do not commit this file\nAPI_KEY=stored-secret-value\n',
    )
    expect(await readFile(join(folder, '.gitignore'), 'utf8')).toBe('.env\n')
    expect(harness.assertLeaseCurrent).toHaveBeenCalledTimes(4)
    expect(harness.recordAudit).toHaveBeenCalledWith('env.exported', expect.objectContaining({
      projectId: 'project-1',
      environmentId: 'environment-local',
      envKeys: ['API_KEY'],
    }))
    expect(harness.confirmProjectExportSummary).toHaveBeenCalledWith(expect.objectContaining({
      projectName: 'Project One',
      environmentName: 'Local',
      path: folder,
      mappings: ['API_KEY ← Stored Secret / value'],
      addToGitignore: true,
    }))
  })

  it('rejects inactive-project commercial policy before plaintext confirmation or writes', async () => {
    const folder = await temporaryFolder()
    const confirmProjectEnvExport = vi.fn(() => ({ success: true as const }))
    const harness = exportHarness({
      folder,
      confirmProjectEnvExport,
      acquireProjectExportLease: async () => {
        throw new Error('Activate this project before scanning, changing mappings, or exporting .env')
      },
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: expect.stringContaining('Activate this project'),
    })
    expect(confirmProjectEnvExport).not.toHaveBeenCalled()
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('rejects a stored cloud environment before plaintext confirmation or writes', async () => {
    const folder = await temporaryFolder()
    const confirmProjectEnvExport = vi.fn(() => ({ success: true as const }))
    const harness = exportHarness({ folder, confirmProjectEnvExport, environmentKind: 'cloud' })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: 'Only a stored local environment can be exported to .env',
    })
    expect(confirmProjectEnvExport).not.toHaveBeenCalled()
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
  })

  it('requires the main-owned destination and mapping summary before user-presence approval', async () => {
    const folder = await temporaryFolder()
    const confirmProjectEnvExport = vi.fn(() => ({ success: true as const }))
    const harness = exportHarness({
      folder,
      confirmProjectEnvExport,
      confirmProjectExportSummary: async () => false,
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      cancelled: true,
    })
    expect(confirmProjectEnvExport).not.toHaveBeenCalled()
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
  })

  it('escapes control characters in the displayed destination without changing the write path', async () => {
    const parent = await temporaryFolder()
    const folder = join(parent, 'project\nDestination: attacker')
    await mkdir(folder)
    const harness = exportHarness({ folder })

    await expect(harness.exportEnv()).resolves.toMatchObject({ success: true })
    expect(harness.confirmProjectExportSummary).toHaveBeenCalledWith(expect.objectContaining({
      path: expect.stringContaining('project\\u000ADestination: attacker'),
    }))
    const displayed = harness.confirmProjectExportSummary.mock.calls[0]?.[0] as { path: string }
    expect(displayed.path).not.toContain('\n')
    await expect(readFile(join(folder, '.env'), 'utf8')).resolves.toContain('API_KEY=stored-secret-value')
  })

  it('commits nothing when the vault revision changes during confirmation', async () => {
    const folder = await temporaryFolder()
    let revision = 7
    const harness = exportHarness({
      folder,
      getVaultRevision: () => revision,
      confirmProjectEnvExport: vi.fn(() => {
        revision = 8
        return { success: true as const }
      }),
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({ success: false })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('commits nothing when commercial eligibility changes during confirmation', async () => {
    const folder = await temporaryFolder()
    let leaseCurrent = true
    const assertLeaseCurrent = vi.fn(() => {
      if (!leaseCurrent) throw new Error('Project export authorization changed; try again')
    })
    const harness = exportHarness({
      folder,
      assertLeaseCurrent,
      confirmProjectEnvExport: vi.fn(() => {
        leaseCurrent = false
        return { success: true as const }
      }),
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: 'Project export authorization changed; try again',
    })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('commits nothing when the vault locks or its key changes during confirmation', async () => {
    const folder = await temporaryFolder()
    const originalKey = Buffer.alloc(32, 1)
    let currentKey: Buffer | null = originalKey
    const harness = exportHarness({
      folder,
      getVaultKey: () => currentKey,
      confirmProjectEnvExport: vi.fn(() => {
        currentKey = Buffer.alloc(32, 2)
        return { success: true as const }
      }),
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({ success: false })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })
})

function exportHarness(options: {
  folder: string
  environmentKind?: 'local' | 'cloud'
  getVaultKey?: () => Buffer | null
  getVaultRevision?: () => number
  confirmProjectEnvExport?: (prompt: string) => { success: true } | { success: false; error: string }
  confirmProjectExportSummary?: (summary: unknown) => Promise<boolean>
  assertLeaseCurrent?: () => void
  acquireProjectExportLease?: () => Promise<{ assertCurrent(): void }>
}) {
  const handlers = new Map<string, IpcHandler>()
  const ipcMain = {
    handle: (channel: string, handler: IpcHandler) => { handlers.set(channel, handler) },
  } as unknown as IpcMain
  const key = Buffer.alloc(32, 1)
  const assertLeaseCurrent = vi.fn(options.assertLeaseCurrent ?? (() => undefined))
  const confirmProjectEnvExport = vi.fn(options.confirmProjectEnvExport ?? (() => ({ success: true as const })))
  const recordAudit = vi.fn()
  const confirmProjectExportSummary = vi.fn(options.confirmProjectExportSummary ?? (async () => true))
  const vault = {
    version: 2,
    revision: 7,
    root: {
      id: 'root',
      name: 'My Vault',
      children: [],
      secrets: [{
        id: 'secret-1', name: 'Stored Secret',
        scope: 'development',
        fields: [{ id: 'field-1', key: 'value', value: 'stored-secret-value' }],
      }],
    },
    envProjects: [{
      id: 'project-1',
      name: 'Project One',
      path: '/renderer-must-not-control-this',
      entries: [],
      addToGitignore: false,
      environments: [{
        id: 'environment-local',
        name: 'Local',
        kind: options.environmentKind ?? 'local',
        path: options.folder,
        entries: [{ envKey: 'API_KEY', secretId: 'secret-1', fieldId: 'field-1', fieldKey: 'value' }],
        addToGitignore: true,
      }],
    }],
  }

  registerProjectIpc(ipcMain, {
    getVaultKey: options.getVaultKey ?? (() => key),
    getVaultRevision: options.getVaultRevision ?? (() => 7),
    readVault: async () => vault,
    authController: { confirmProjectEnvExport } as unknown as AuthController,
    recordAudit,
    acquireProjectExportLease: options.acquireProjectExportLease
      ?? (async () => ({ assertCurrent: assertLeaseCurrent })),
    confirmProjectExportSummary,
    pathCapabilities: new ProjectPathCapabilityStore(),
  })

  const handler = handlers.get(projectIpcContracts.exportEnv.channel)
  if (!handler) throw new Error('Project export handler was not registered')
  return {
    assertLeaseCurrent,
    confirmProjectExportSummary,
    recordAudit,
    exportEnv: () => handler({}, {
      projectId: 'project-1',
      environmentId: 'environment-local',
    }),
  }
}

async function temporaryFolder(): Promise<string> {
  const folder = await mkdtemp(join(tmpdir(), 'vaultage-project-export-'))
  temporaryFolders.push(folder)
  return folder
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false
    throw error
  }
}
