import { afterEach, describe, expect, it, vi } from 'vitest'
import { EventEmitter } from 'events'
import { mkdir, mkdtemp, readFile, realpath, rm, stat, writeFile } from 'fs/promises'
import { tmpdir } from 'os'
import { join } from 'path'
import type { IpcMain } from 'electron'
import type { AuditEventType } from './audit'
import { AuthController } from './auth'
import { registerProjectIpc } from './projectIpc'
import { CREATE_PROJECT_GRANT_TARGET, ProjectPathCapabilityStore } from './projectCapabilities'
import { projectIpcContracts } from '../shared/projectIpcContracts'

type ElectronIpcHandler = Parameters<IpcMain['handle']>[1]
type IpcHandler = (event: unknown, payload: unknown) => Promise<unknown>
type AuthConfirmation = ReturnType<AuthController['confirmProjectEnvExport']>

const temporaryFolders: string[] = []

afterEach(async () => {
  await Promise.all(temporaryFolders.splice(0).map(path => rm(path, { recursive: true, force: true })))
})

describe('project folder picker IPC boundary', () => {
  it('rejects malformed picker payloads before native dialog or capability access', async () => {
    const { handlers, ipcMain } = fakeIpcMain()
    const key = Buffer.alloc(32, 1)
    registerProjectIpc(ipcMain, {
      getVaultKey: () => key,
      getVaultRevision: () => 1,
      readVault: async () => ({ revision: 1 }),
      beginSessionOperation: () => null,
      authController: testAuthController(),
      recordAudit: vi.fn(),
      recordAuditDurable: vi.fn(async () => undefined),
      acquireProjectScanLease: vi.fn(async () => ({ assertCurrent: async () => undefined })),
      acquireProjectExportLease: vi.fn(async () => ({ assertCurrent: () => undefined })),
      confirmProjectExportSummary: vi.fn(async () => true),
      pathCapabilities: new ProjectPathCapabilityStore(),
    })

    const handler = handlers.get(projectIpcContracts.pickFolder.channel)
    if (!handler) throw new Error('Project folder picker handler was not registered')
    const event = { sender: { id: 23 } }

    await expect(handler(event, undefined)).rejects.toThrow('must be an object')
    await expect(handler(event, { purpose: 'unsupported-purpose' }))
      .rejects.toThrow('Invalid project folder picker purpose')
    await expect(handler(event, { purpose: 'scan-parent', projectId: 'project-1' }))
      .rejects.toThrow('cannot target')
  })
})

describe('project .env export IPC', () => {
  it('derives the target, mappings, and gitignore policy from the stored local environment', async () => {
    const folder = await temporaryFolder()
    const harness = exportHarness({ folder })

    const result = await harness.exportEnv()

    expect(result).toMatchObject({
      success: true,
      status: { envFile: 'created', gitignore: 'created' },
    })
    expect(await readFile(join(folder, '.env'), 'utf8')).toBe(
      '# Generated by Vaultage - do not commit this file\nAPI_KEY=stored-secret-value\n',
    )
    expect(await readFile(join(folder, '.gitignore'), 'utf8')).toBe('.env\n')
    expect(harness.assertLeaseCurrent).toHaveBeenCalledTimes(6)
    expect(harness.recordAudit).toHaveBeenCalledWith('env.exported', expect.objectContaining({
      projectId: 'project-1',
      environmentId: 'environment-local',
      envKeys: ['API_KEY'],
    }))
    expect(harness.confirmProjectExportSummary).toHaveBeenCalledWith(expect.objectContaining({
      projectName: 'Project One',
      environmentName: 'Local',
      path: folder,
      mappings: ['API_KEY ← Stored Secret / value'],
      addToGitignore: true,
    }))
  })

  it('rejects inactive-project commercial policy before plaintext confirmation or writes', async () => {
    const folder = await temporaryFolder()
    const confirmProjectEnvExport = vi.fn(() => ({ success: true as const }))
    const harness = exportHarness({
      folder,
      confirmProjectEnvExport,
      acquireProjectExportLease: async () => {
        throw new Error('Activate this project before scanning, changing mappings, or exporting .env')
      },
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: expect.stringContaining('Activate this project'),
    })
    expect(confirmProjectEnvExport).not.toHaveBeenCalled()
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('writes no plaintext when the authorization audit cannot be made durable', async () => {
    const folder = await temporaryFolder()
    const harness = exportHarness({
      folder,
      recordAuditDurable: async type => {
        if (type === 'vault.plaintext_release.authorized') throw new Error('audit storage unavailable')
      },
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: expect.stringContaining('audit storage unavailable'),
    })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('rejects a stored cloud environment before plaintext confirmation or writes', async () => {
    const folder = await temporaryFolder()
    const confirmProjectEnvExport = vi.fn(() => ({ success: true as const }))
    const harness = exportHarness({ folder, confirmProjectEnvExport, environmentKind: 'cloud' })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: 'Only a stored local environment can be exported to .env',
    })
    expect(confirmProjectEnvExport).not.toHaveBeenCalled()
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
  })

  it('requires the main-owned destination and mapping summary before user-presence approval', async () => {
    const folder = await temporaryFolder()
    const confirmProjectEnvExport = vi.fn(() => ({ success: true as const }))
    const harness = exportHarness({
      folder,
      confirmProjectEnvExport,
      confirmProjectExportSummary: async () => false,
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      cancelled: true,
    })
    expect(confirmProjectEnvExport).not.toHaveBeenCalled()
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
  })

  it('escapes control characters in the displayed destination without changing the write path', async () => {
    const parent = await temporaryFolder()
    const folder = join(parent, 'project\nDestination: attacker')
    await mkdir(folder)
    const harness = exportHarness({ folder })

    await expect(harness.exportEnv()).resolves.toMatchObject({ success: true })
    expect(harness.confirmProjectExportSummary).toHaveBeenCalledWith(expect.objectContaining({
      path: expect.stringContaining('project\\u000ADestination: attacker'),
    }))
    const displayed = harness.confirmProjectExportSummary.mock.calls[0]?.[0] as { path: string }
    expect(displayed.path).not.toContain('\n')
    await expect(readFile(join(folder, '.env'), 'utf8')).resolves.toContain('API_KEY=stored-secret-value')
  })

  it('commits nothing when the vault revision changes during confirmation', async () => {
    const folder = await temporaryFolder()
    let revision = 7
    const harness = exportHarness({
      folder,
      getVaultRevision: () => revision,
      confirmProjectEnvExport: vi.fn(() => {
        revision = 8
        return { success: true as const }
      }),
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({ success: false })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('commits nothing when commercial eligibility changes during confirmation', async () => {
    const folder = await temporaryFolder()
    let leaseCurrent = true
    const assertLeaseCurrent = vi.fn(() => {
      if (!leaseCurrent) throw new Error('Project export authorization changed; try again')
    })
    const harness = exportHarness({
      folder,
      assertLeaseCurrent,
      confirmProjectEnvExport: vi.fn(() => {
        leaseCurrent = false
        return { success: true as const }
      }),
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({
      success: false,
      error: 'Project export authorization changed; try again',
    })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })

  it('commits nothing when the vault locks or its key changes during confirmation', async () => {
    const folder = await temporaryFolder()
    const originalKey = Buffer.alloc(32, 1)
    let currentKey: Buffer | null = originalKey
    const harness = exportHarness({
      folder,
      getVaultKey: () => currentKey,
      confirmProjectEnvExport: vi.fn(() => {
        currentKey = Buffer.alloc(32, 2)
        return { success: true as const }
      }),
    })

    await expect(harness.exportEnv()).resolves.toMatchObject({ success: false })
    await expect(pathExists(join(folder, '.env'))).resolves.toBe(false)
    await expect(pathExists(join(folder, '.gitignore'))).resolves.toBe(false)
  })
})

describe('project scan policy IPC', () => {
  it('withholds an exact scan result when its commercial lease becomes stale', async () => {
    const folder = await temporaryFolder()
    await writeFile(join(folder, 'package.json'), '{"name":"scan-policy"}')
    const harness = await scanHarness({
      folder,
      assertLeaseCurrent: () => { throw new Error('Project scan authorization changed; try again') },
    })

    await expect(harness.scan()).resolves.toMatchObject({
      success: false,
      error: 'Project scan authorization changed; try again',
    })
    expect(harness.acquireProjectScanLease).toHaveBeenCalledWith(
      expect.any(Object),
      await realpath(folder),
      undefined,
    )
  })

  it('withholds an exact scan result when the vault changes during scanning', async () => {
    const folder = await temporaryFolder()
    await writeFile(join(folder, 'package.json'), '{"name":"scan-revision"}')
    let revision = 7
    const harness = await scanHarness({
      folder,
      getVaultRevision: () => revision,
      assertLeaseCurrent: () => { revision = 8 },
    })

    await expect(harness.scan()).resolves.toMatchObject({
      success: false,
      error: 'Vault changed during project scan; try again',
    })
  })

  it('rejects discovery before scanning or granting an unauthorized candidate', async () => {
    const parent = await temporaryFolder()
    const candidate = join(parent, 'candidate-app')
    await mkdir(candidate)
    await writeFile(join(candidate, 'package.json'), '{"name":"candidate-app"}')
    const harness = await scanHarness({
      folder: parent,
      discovery: true,
      acquireProjectScanLease: async () => {
        throw new Error('The Free plan active-project limit is full')
      },
    })

    await expect(harness.discover()).resolves.toMatchObject({
      success: false,
      error: 'The Free plan active-project limit is full',
    })
    expect(harness.acquireProjectScanLease).toHaveBeenCalledWith(
      expect.any(Object),
      await realpath(candidate),
      undefined,
    )
    await expect(harness.pathCapabilities.requireProjectFolder(
      harness.rendererId,
      candidate,
      CREATE_PROJECT_GRANT_TARGET,
    )).rejects.toThrow('access expired')
  })

  it('withholds discovered candidates and grants when authorization expires after scanning', async () => {
    const parent = await temporaryFolder()
    const candidate = join(parent, 'candidate-app')
    await mkdir(candidate)
    await writeFile(join(candidate, 'package.json'), '{"name":"candidate-app"}')
    const harness = await scanHarness({
      folder: parent,
      discovery: true,
      assertLeaseCurrent: async () => {
        throw new Error('Project scan authorization changed; try again')
      },
    })

    await expect(harness.discover()).resolves.toMatchObject({
      success: false,
      error: 'Project scan authorization changed; try again',
    })
    await expect(harness.pathCapabilities.requireProjectFolder(
      harness.rendererId,
      candidate,
      CREATE_PROJECT_GRANT_TARGET,
    )).rejects.toThrow('access expired')
  })
})

function exportHarness(options: {
  folder: string
  environmentKind?: 'local' | 'cloud'
  getVaultKey?: () => Buffer | null
  getVaultRevision?: () => number
  confirmProjectEnvExport?: (prompt: string) => AuthConfirmation
  confirmProjectExportSummary?: (summary: unknown) => Promise<boolean>
  assertLeaseCurrent?: () => void
  acquireProjectExportLease?: () => Promise<{ assertCurrent(): void }>
  recordAuditDurable?: (type: AuditEventType, details?: Record<string, unknown>) => Promise<void>
}) {
  const { handlers, ipcMain } = fakeIpcMain()
  const key = Buffer.alloc(32, 1)
  const assertLeaseCurrent = vi.fn(options.assertLeaseCurrent ?? (() => undefined))
  const confirmProjectEnvExport = vi.fn(options.confirmProjectEnvExport ?? (() => ({ success: true as const })))
  const recordAudit = vi.fn()
  const confirmProjectExportSummary = vi.fn(options.confirmProjectExportSummary ?? (async () => true))
  const vault = {
    version: 2,
    revision: 7,
    root: {
      id: 'root',
      name: 'My Vault',
      children: [],
      secrets: [{
        id: 'secret-1', name: 'Stored Secret',
        scope: 'development',
        fields: [{ id: 'field-1', key: 'value', value: 'stored-secret-value' }],
      }],
    },
    envProjects: [{
      id: 'project-1',
      name: 'Project One',
      path: '/renderer-must-not-control-this',
      entries: [],
      addToGitignore: false,
      environments: [{
        id: 'environment-local',
        name: 'Local',
        kind: options.environmentKind ?? 'local',
        path: options.folder,
        entries: [{ envKey: 'API_KEY', secretId: 'secret-1', fieldId: 'field-1', fieldKey: 'value' }],
        addToGitignore: true,
      }],
    }],
  }

  registerProjectIpc(ipcMain, {
    getVaultKey: options.getVaultKey ?? (() => key),
    getVaultRevision: options.getVaultRevision ?? (() => 7),
    readVault: async () => vault,
    beginSessionOperation: () => ({ epoch: 1, assertCurrent: () => undefined, release: () => undefined }),
    authController: testAuthController(confirmProjectEnvExport),
    recordAudit,
    recordAuditDurable: options.recordAuditDurable
      ?? (async (type, details) => { recordAudit(type, details) }),
    acquireProjectScanLease: async () => ({ assertCurrent: async () => undefined }),
    acquireProjectExportLease: options.acquireProjectExportLease
      ?? (async () => ({ assertCurrent: assertLeaseCurrent })),
    confirmProjectExportSummary,
    pathCapabilities: new ProjectPathCapabilityStore(),
  })

  const handler = handlers.get(projectIpcContracts.exportEnv.channel)
  if (!handler) throw new Error('Project export handler was not registered')
  return {
    assertLeaseCurrent,
    confirmProjectExportSummary,
    recordAudit,
    exportEnv: () => handler({}, {
      projectId: 'project-1',
      environmentId: 'environment-local',
    }),
  }
}

async function scanHarness(options: {
  folder: string
  discovery?: boolean
  getVaultRevision?: () => number
  assertLeaseCurrent?: () => void | Promise<void>
  acquireProjectScanLease?: () => Promise<{ assertCurrent(): Promise<void> }>
}) {
  const { handlers, ipcMain } = fakeIpcMain()
  const key = Buffer.alloc(32, 1)
  const rendererId = 91
  const pathCapabilities = new ProjectPathCapabilityStore()
  await pathCapabilities.grantFolder(
    rendererId,
    options.folder,
    options.discovery ? 'scan-parent' : 'project-local-path',
  )
  const vault = {
    version: 2,
    revision: 7,
    root: { id: 'root', name: 'My Vault', children: [], secrets: [] },
    envProjects: [],
  }
  const acquireProjectScanLease = vi.fn(options.acquireProjectScanLease
    ?? (async () => ({ assertCurrent: async () => options.assertLeaseCurrent?.() })))

  registerProjectIpc(ipcMain, {
    getVaultKey: () => key,
    getVaultRevision: options.getVaultRevision ?? (() => 7),
    readVault: async () => vault,
    beginSessionOperation: () => ({ epoch: 1, assertCurrent: () => undefined, release: () => undefined }),
    authController: testAuthController(),
    recordAudit: vi.fn(),
    recordAuditDurable: vi.fn(async () => undefined),
    acquireProjectScanLease,
    acquireProjectExportLease: async () => ({ assertCurrent: () => undefined }),
    confirmProjectExportSummary: async () => true,
    pathCapabilities,
  })

  const event = { sender: { id: rendererId } }
  const scan = handlers.get(projectIpcContracts.scan.channel)
  const discover = handlers.get(projectIpcContracts.discover.channel)
  if (!scan || !discover) throw new Error('Project scan handlers were not registered')
  return {
    acquireProjectScanLease,
    pathCapabilities,
    rendererId,
    scan: () => scan(event, { path: options.folder }),
    discover: () => discover(event, { parentPath: options.folder }),
  }
}

function fakeIpcMain(): {
  handlers: Map<string, IpcHandler>
  ipcMain: IpcMain
} {
  const handlers = new Map<string, IpcHandler>()
  const ipcMain = Object.assign(new EventEmitter(), {
    handle: (channel: string, handler: ElectronIpcHandler) => {
      handlers.set(channel, async (event, payload) => Reflect.apply(handler, undefined, [event, payload]))
    },
    handleOnce: (channel: string, handler: ElectronIpcHandler) => {
      handlers.set(channel, async (event, payload) => Reflect.apply(handler, undefined, [event, payload]))
    },
    removeHandler: (channel: string) => { handlers.delete(channel) },
  })
  return { handlers, ipcMain }
}

function testAuthController(
  confirmProjectEnvExport: (prompt: string) => AuthConfirmation = () => ({ success: true }),
): AuthController {
  return new TestAuthController(confirmProjectEnvExport)
}

class TestAuthController extends AuthController {
  constructor(private readonly confirm: (prompt: string) => AuthConfirmation) {
    super({
      storage: {
        ensureVaultDir: async () => undefined,
        getAuthStateStatus: async () => 'missing',
        readCredentials: async () => ({ paramsRaw: '{}', wrappedKey: Buffer.alloc(0) }),
        readVault: async () => ({}),
        createVaultState: async () => undefined,
        commitAuthCredentials: async () => undefined,
        commitRestoredVaultState: async () => undefined,
      },
      keychain: {
        isMac: false,
        store: () => false,
        retrieve: () => ({ key: null, cancelled: false, notFound: true, authFailed: false }),
        remove: () => false,
      },
      session: {
        beginOperation: () => null,
        leaseCurrentKey: () => null,
        installKey: () => false,
      },
      recordAudit: () => undefined,
      randomId: () => 'test-id',
    })
  }

  override confirmProjectEnvExport(prompt: string): AuthConfirmation {
    return this.confirm(prompt)
  }
}

async function temporaryFolder(): Promise<string> {
  const folder = await mkdtemp(join(tmpdir(), 'vaultage-project-export-'))
  temporaryFolders.push(folder)
  return folder
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false
    throw error
  }
}
